package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi2"
	"github.com/getkin/kin-openapi/openapi2conv"
	"github.com/getkin/kin-openapi/openapi3"
	"gopkg.in/yaml.v3"
)

type config struct {
	schemaPath string
	outputDir  string
	modulePath string
}

func main() {
	var cfg config
	flag.StringVar(&cfg.schemaPath, "schema", "api/schema.yaml", "path to the OpenAPI or Swagger schema")
	flag.StringVar(&cfg.outputDir, "output", ".", "project root where generated files are written")
	flag.StringVar(&cfg.modulePath, "module", "autogen", "Go module path used by generated imports")
	flag.Parse()

	data, err := ioutil.ReadFile(cfg.schemaPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read %s: %v\n", cfg.schemaPath, err)
		os.Exit(2)
	}

	// Parse either OpenAPI 3 or Swagger 2 and normalize it to OpenAPI 3.
	var version struct {
		Swagger     string               `yaml:"swagger"`
		Definitions map[string]yaml.Node `yaml:"definitions"`
	}
	if err := yaml.Unmarshal(data, &version); err != nil {
		fmt.Fprintf(os.Stderr, "failed to inspect schema version: %v\n", err)
		os.Exit(3)
	}

	var doc *openapi3.T
	var swaggerDefinitions map[string]*openapi2.SchemaRef
	if version.Swagger != "" || len(version.Definitions) > 0 {
		var swaggerDoc openapi2.T
		var raw map[string]interface{}
		if err := yaml.Unmarshal(data, &raw); err != nil {
			fmt.Fprintf(os.Stderr, "failed to parse Swagger 2 YAML: %v\n", err)
			os.Exit(3)
		}
		jsonData, err := json.Marshal(raw)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to convert Swagger 2 YAML to JSON: %v\n", err)
			os.Exit(3)
		}
		if err := json.Unmarshal(jsonData, &swaggerDoc); err != nil {
			fmt.Fprintf(os.Stderr, "failed to load Swagger 2 schema: %v\n", err)
			os.Exit(3)
		}
		if swaggerDoc.Swagger == "" {
			swaggerDoc.Swagger = "2.0"
		}
		swaggerDefinitions = swaggerDoc.Definitions
		doc, err = openapi2conv.ToV3(&swaggerDoc)
	} else {
		loader := openapi3.NewLoader()
		doc, err = loader.LoadFromData(data)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to load OpenAPI: %v\n", err)
		os.Exit(3)
	}
	if doc == nil {
		loader := openapi3.NewLoader()
		doc, err = loader.LoadFromData(data)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to load OpenAPI fallback: %v\n", err)
			os.Exit(3)
		}
		if doc.Components == nil {
			doc.Components = &openapi3.Components{}
		}
		doc.Components.Schemas = openapi2conv.ToV3Schemas(swaggerDefinitions)
		if doc.OpenAPI == "" {
			doc.OpenAPI = "3.0.3"
		}
		if doc.Info == nil {
			doc.Info = &openapi3.Info{Title: "Generated API", Version: "0.0.0"}
		}
	}

	// Ensure directories
	dtoDir := filepath.Join(cfg.outputDir, "internal", "dto")
	restDir := filepath.Join(cfg.outputDir, "internal", "api", "rest")
	swaggerDir := filepath.Join(cfg.outputDir, "docs", "swagger")
	_ = os.MkdirAll(dtoDir, 0755)
	_ = os.MkdirAll(restDir, 0755)
	_ = os.MkdirAll(swaggerDir, 0755)
	collectInlineSchemas(doc)

	// Generate DTOs
	if err := generateDTOs(doc, dtoDir); err != nil {
		fmt.Fprintf(os.Stderr, "generateDTOs error: %v\n", err)
		os.Exit(4)
	}

	// Generate handlers
	if err := generateHandlers(doc, cfg.modulePath, restDir); err != nil {
		fmt.Fprintf(os.Stderr, "generateHandlers error: %v\n", err)
		os.Exit(5)
	}

	// Dump swagger JSON (prettified)
	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to encode swagger: %v\n", err)
		os.Exit(6)
	}
	if err := ioutil.WriteFile(filepath.Join(swaggerDir, "swagger.json"), out, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write swagger: %v\n", err)
		os.Exit(6)
	}

	// Ensure index.html for Swagger UI
	indexHTML := `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Swagger UI</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@4/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@4/swagger-ui-bundle.js"></script>
    <script>
      const ui = SwaggerUIBundle({ url: 'swagger.json', dom_id: '#swagger-ui' })
    </script>
  </body>
</html>`

	_ = ioutil.WriteFile(filepath.Join(swaggerDir, "index.html"), []byte(indexHTML), 0644)

	fmt.Printf("generation complete: %s, %s, %s\n", dtoDir, restDir, swaggerDir)
}

func generateDTOs(doc *openapi3.T, outputDir string) error {
	var buf bytes.Buffer
	buf.WriteString("package dto\n\n")
	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	names := make([]string, 0, len(doc.Components.Schemas))
	for n := range doc.Components.Schemas {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, name := range names {
		ref := doc.Components.Schemas[name]
		goName := sanitizeTypeName(name)
		if ref == nil {
			continue
		}
		if ref.Ref != "" {
			targetName := sanitizeTypeName(schemaRefName(ref.Ref))
			if targetName != goName {
				buf.WriteString(fmt.Sprintf("type %s = %s\n\n", goName, targetName))
				continue
			}
		}
		schema := resolveSchemaRef(ref, doc.Components.Schemas)
		if schema == nil {
			continue
		}
		if schema.Type != nil && (schema.Type.Is("object") || len(schema.Properties) > 0) {
			buf.WriteString("type " + goName + " struct {\n")
			// properties
			props := make([]string, 0, len(schema.Properties))
			for p := range schema.Properties {
				props = append(props, p)
			}
			sort.Strings(props)
			for _, p := range props {
				sref := schema.Properties[p]
				fieldName := sanitizeFieldName(p)
				fieldType := resolveSchemaToGoType(sref, p, doc.Components.Schemas)
				tag := fmt.Sprintf("`json:\"%s,omitempty\"`", p)
				buf.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, fieldType, tag))
			}
			buf.WriteString("}\n\n")
		} else {
			// simple alias
			t := resolveSchemaToGoType(ref, name, doc.Components.Schemas)
			buf.WriteString(fmt.Sprintf("type %s %s\n\n", goName, t))
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// write unformatted for debugging
		return ioutil.WriteFile(filepath.Join(outputDir, "dto.go"), buf.Bytes(), 0644)
	}
	return ioutil.WriteFile(filepath.Join(outputDir, "dto.go"), formatted, 0644)
}

func generateHandlers(doc *openapi3.T, modulePath, outputDir string) error {
	entries, err := os.ReadDir(outputDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), "_generated.go") {
			if err := os.Remove(filepath.Join(outputDir, entry.Name())); err != nil {
				return err
			}
		}
	}

	// create a basic handler for each operation
	paths := doc.Paths.Keys()
	sort.Strings(paths)
	for _, p := range paths {
		item := doc.Paths.Value(p)
		ops := []struct {
			method string
			op     *openapi3.Operation
		}{
			{"Get", item.Get},
			{"Post", item.Post},
			{"Put", item.Put},
			{"Delete", item.Delete},
			{"Patch", item.Patch},
		}
		for _, operation := range ops {
			method, op := operation.method, operation.op
			if op == nil {
				continue
			}
			name := operationName(op, method, p)
			handlerName := sanitizeFuncName(name)
			baseName := snakeCase(handlerName)
			requestSchema := operationRequestSchema(op)
			headerSchema := operationHeaderSchema(op)
			var buf bytes.Buffer
			buf.WriteString("package rest\n\n")
			buf.WriteString("import (\n\t\"github.com/valyala/fasthttp\"\n")
			if requestSchema != nil || headerSchema != nil {
				buf.WriteString(fmt.Sprintf("\t\"%s/internal/dto\"\n", modulePath))
			}
			buf.WriteString(")\n\n")
			if requestSchema != nil || headerSchema != nil {
				buf.WriteString("var _ = struct {\n")
				if headerSchema != nil {
					buf.WriteString(fmt.Sprintf("\theaders dto.%sRequestHeaders\n", sanitizeTypeName(baseName)))
				}
				if requestSchema != nil {
					buf.WriteString(fmt.Sprintf("\tbody dto.%sRequestBody\n", sanitizeTypeName(baseName)))
				}
				buf.WriteString("}{}\n\n")
			}
			buf.WriteString(fmt.Sprintf("func (a *API) %s(ctx *fasthttp.RequestCtx) {\n", handlerName))
			buf.WriteString("\t// TODO: implementation\n")
			buf.WriteString("}\n\n")

			formatted, err := format.Source(buf.Bytes())
			if err != nil {
				return fmt.Errorf("format handler %s: %w", handlerName, err)
			}
			filename := filepath.Join(outputDir, snakeCase(handlerName)+".go")
			if err := ioutil.WriteFile(filename, formatted, 0644); err != nil {
				return fmt.Errorf("write handler %s: %w", handlerName, err)
			}
		}
	}
	return nil
}

func collectInlineSchemas(doc *openapi3.T) {
	if doc.Components == nil {
		doc.Components = &openapi3.Components{}
	}
	if doc.Components.Schemas == nil {
		doc.Components.Schemas = make(map[string]*openapi3.SchemaRef)
	}

	for _, p := range doc.Paths.Keys() {
		item := doc.Paths.Value(p)
		for _, operation := range []*openapi3.Operation{item.Get, item.Post, item.Put, item.Delete, item.Patch} {
			if operation == nil {
				continue
			}
			name := operationName(operation, "", p)
			baseName := snakeCase(sanitizeFuncName(name))

			requestSchema := operationRequestSchema(operation)
			if requestSchema != nil {
				doc.Components.Schemas[baseName+"_request_body"] = requestSchema
			}

			headerSchema := operationHeaderSchema(operation)
			if headerSchema != nil {
				doc.Components.Schemas[baseName+"_request_headers"] = &openapi3.SchemaRef{Value: headerSchema}
			}
		}
	}
}

func operationHeaderSchema(operation *openapi3.Operation) *openapi3.Schema {
	headerSchema := &openapi3.Schema{Type: &openapi3.Types{"object"}, Properties: openapi3.Schemas{}}
	for _, parameter := range operation.Parameters {
		if parameter == nil || parameter.Value == nil || parameter.Value.In != "header" {
			continue
		}
		if schema := parameterSchema(parameter.Value); schema != nil {
			headerSchema.Properties[parameter.Value.Name] = schema
		}
	}
	if len(headerSchema.Properties) == 0 {
		return nil
	}
	return headerSchema
}

func operationRequestSchema(operation *openapi3.Operation) *openapi3.SchemaRef {
	if operation.RequestBody != nil && operation.RequestBody.Value != nil {
		return firstRequestSchema(operation.RequestBody.Value.Content)
	}
	for _, parameter := range operation.Parameters {
		if parameter != nil && parameter.Value != nil && parameter.Value.In == "body" {
			return parameterSchema(parameter.Value)
		}
	}
	return nil
}

func parameterSchema(parameter *openapi3.Parameter) *openapi3.SchemaRef {
	if parameter.Schema != nil {
		return parameter.Schema
	}
	if parameter.Extensions == nil {
		return nil
	}
	typeName, ok := parameter.Extensions["type"].(string)
	if !ok || typeName == "" {
		return nil
	}
	schema := &openapi3.Schema{Type: &openapi3.Types{typeName}, Format: parameterFormat(parameter.Extensions)}
	return &openapi3.SchemaRef{Value: schema}
}

func parameterFormat(extensions map[string]interface{}) string {
	format, _ := extensions["format"].(string)
	return format
}

func schemaRefName(ref string) string {
	if index := strings.LastIndex(ref, "/"); index >= 0 {
		return ref[index+1:]
	}
	return ref
}

func firstRequestSchema(content openapi3.Content) *openapi3.SchemaRef {
	if schema := content["application/json"]; schema != nil {
		return schema.Schema
	}
	for _, mediaType := range content {
		return mediaType.Schema
	}
	return nil
}

func operationName(operation *openapi3.Operation, method, route string) string {
	if operation != nil && operation.OperationID != "" {
		return operation.OperationID
	}
	parts := strings.Split(route, "/")
	nameParts := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" || strings.EqualFold(part, "api") || (len(part) > 1 && part[0] == 'v' && allDigits(part[1:])) || (strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}")) {
			continue
		}
		nameParts = append(nameParts, part)
	}
	if len(nameParts) == 0 {
		return method + "Handler"
	}
	return strings.Join(nameParts, "_")
}

func allDigits(value string) bool {
	if value == "" {
		return false
	}
	for _, char := range value {
		if char < '0' || char > '9' {
			return false
		}
	}
	return true
}

func snakeCase(value string) string {
	var builder strings.Builder
	for index, char := range value {
		if char >= 'A' && char <= 'Z' {
			if index > 0 {
				builder.WriteByte('_')
			}
			builder.WriteByte(byte(char + ('a' - 'A')))
		} else if char == '-' || char == ' ' {
			builder.WriteByte('_')
		} else {
			builder.WriteRune(char)
		}
	}
	return strings.Trim(builder.String(), "_")
}

func sanitizeTypeName(s string) string {
	// remove non-alphanum and title case
	re := regexp.MustCompile("[^a-zA-Z0-9]+")
	parts := re.Split(s, -1)
	out := ""
	for _, p := range parts {
		if p == "" {
			continue
		}
		out += strings.Title(p)
	}
	return out
}

func sanitizeFieldName(s string) string {
	// camel-case
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ' ' })
	out := ""
	for _, p := range parts {
		if p == "" {
			continue
		}
		out += strings.Title(p)
	}
	// ensure first char is upper
	if out == "" {
		return "F"
	}
	return out
}

func sanitizeFuncName(s string) string {
	name := sanitizeTypeName(s)
	if name == "" {
		return "handler"
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func pathToFuncName(p string) string {
	// /users/{id} -> UsersById
	parts := strings.Split(p, "/")
	out := ""
	for _, part := range parts {
		if part == "" {
			continue
		}
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			out += "By" + strings.Title(strings.Trim(part, "{}"))
		} else {
			out += strings.Title(part)
		}
	}
	return out
}

func resolveSchemaToGoType(ref *openapi3.SchemaRef, propName string, schemas openapi3.Schemas) string {
	if ref != nil && ref.Ref != "" {
		return sanitizeTypeName(schemaRefName(ref.Ref))
	}
	schema := resolveSchemaRef(ref, schemas)
	if schema == nil {
		return "interface{}"
	}
	if schema.Type != nil && schema.Type.Is("array") {
		if schema.Items != nil {
			return "[]" + resolveSchemaToGoType(schema.Items, propName, schemas)
		}
		return "[]interface{}"
	}
	if schema.Type != nil && schema.Type.Is("object") {
		// anonymous struct
		var b strings.Builder
		b.WriteString("struct {\n")
		props := make([]string, 0, len(schema.Properties))
		for p := range schema.Properties {
			props = append(props, p)
		}
		sort.Strings(props)
		for _, p := range props {
			f := schema.Properties[p]
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", sanitizeFieldName(p), resolveSchemaToGoType(f, p, schemas), p))
		}
		b.WriteString("}")
		return b.String()
	}
	return simpleType(schema)
}

func resolveSchemaRef(ref *openapi3.SchemaRef, schemas openapi3.Schemas) *openapi3.Schema {
	if ref == nil {
		return nil
	}
	if ref.Value != nil {
		return ref.Value
	}
	if ref.Ref == "" {
		return nil
	}
	component, ok := schemas[schemaRefName(ref.Ref)]
	if !ok || component == ref {
		return nil
	}
	return resolveSchemaRef(component, schemas)
}

func simpleType(s *openapi3.Schema) string {
	if s.Type == nil {
		return "interface{}"
	}
	switch {
	case s.Type.Is("string"):
		return "string"
	case s.Type.Is("integer"):
		return "int"
	case s.Type.Is("number"):
		return "float64"
	case s.Type.Is("boolean"):
		return "bool"
	default:
		if s.Format == "int64" {
			return "int64"
		}
		return "interface{}"
	}
}
